[package]
name = "main"
version = "0.1.0"
edition = "2021"

[dependencies]
items = {path = "../items"}
scene_util = {path = "../scene_util"}
save_system = {path = "../save_system"}
libloading = "0.8"
event_system = {path = "../event_system"}