[package]
name = "main"
version = "0.1.0"
edition = "2021"

[dependencies]
scene_manager = {path = "../scene_manager"}
player_manager = {path = "../player/player_manager"}
item_manager = {path = "../items/item_manager"}
item_id = {path = "../items/item_id"}