[package]
name = "scene_3"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["dylib"]

[dependencies]
scene_util = {path = "../../scene_util"}
save_system = {path = "../../save_system"}
event_system = {path = "../../event_system"}